@host = http://localhost:3000

###
GET {{host}}

###
post {{host}}/company/login
Content-Type: application/json

{
    "username": "comp2user",
    "password": "passwor"
}

###
get {{host}}/company/profile
Content-Type: application/json
id: 23


###
get {{host}}/company/companydetails
Content-Type: application/json
id: 1

###
get {{host}}/company/investordetails
Content-Type: application/json
iid:1
cid:23


###
post {{host}}/investor/login
Content-Type: application/json

{
    "username": "abdur0118",
    "password": "user1"   
}

###
post {{host}}/investor/register
Content-Type: application/json

{
    "firstname": "harihar",
    "lastname":"pawar",
    "middlename":"s",
    "pnum":"8532534610",
    "noinvestments": 2,
    "email": "har@example.com",
    "username":"hariD",
    "password":"pass4",
    "aadhar": "782691521298",
    "pan": "AKRRR5441P",
    "account": "02423423335123",
    "bankname":"Punjab national bank",
    "ifsc":"PUNB0436400",
    "branch":"Mumbai",
    "bankpnum":"51342242"

}

###
get {{host}}/investor/profile
id: 2


###
post {{host}}/investor/addshare
Content-Type: application/json

{
    "dateofpurchase": "2020-2-25",
    "numofshares": 10,
    "current":180,
    "purchaseamt":200,
    "iid":5,
    "cid":"AAPL"
}

###
delete {{host}}/investor/deleteshare
Content-Type: application/json
iid: 1
cid: 23
date: "2019-9-8"

###
get {{host}}/investor/investments
Content-Type: application/json
id: 1